Migration: Move from Travis-CI to GitHub Actions
vegastrike/build-system-docker-images pull request #5
Opened 2021-04-10 03:14 UTC by BenjamenMeyer

Migrate the docker image builds from Travis-CI to GitHub Actions

2021-04-10 03:17 UTC, BenjamenMeyer commented
Think I got this right; but needs a solid review by someone more familiar.

2021-04-10 17:20 UTC, Loki1950 approved these changes
Fairly straight forward

2021-04-10 18:27 UTC, stephengtuggy requested changes
A couple of things. One question, and one change request.

Also, I think we need to change the `cibuild` script -- and perhaps another script or two -- to reference `MY_OS_NAME` rather than `TRAVIS_OS`, and `IS_RELEASE` rather than the Travis equivalent. May also need to replace a variable named something like `TRAVIS_VERSION` with its GH Actions equivalent.

2021-04-10 18:27 UTC, stephengtuggy commented on .github/workflows/gh-actions-release.yml
> +    - name: Upload the artifacts
So we need to publish the artifacts to Docker Hub, I believe, rather than a GitHub release. Accordingly, we will need a Docker Hub access token as a secret, included here.

2021-04-10 18:27 UTC, stephengtuggy commented on .github/workflows/codeql.yml
> +      uses: github/codeql-action/analyze@v1
Hmm. Isn't there supposed to be an additional, final step, where the results of the CodeQL analysis are uploaded to GitHub? I thought there was. Maybe not.

2021-04-11 01:28 UTC, BenjamenMeyer commented on .github/workflows/codeql.yml
> +      uses: github/codeql-action/analyze@v1
Don't know. This file was basic pulled straight across without changes.

2021-04-11 01:28 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-release.yml
> +    - name: Upload the artifacts
We might be able to use GH infrastructure instead of Docker Hub, but more investigating would be needed.

2021-04-11 02:32 UTC, stephengtuggy commented on .github/workflows/codeql.yml
> +      uses: github/codeql-action/analyze@v1
I see. In that case, it's probably fine.

2021-04-13 03:46 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-release.yml
> +    - name: Upload the artifacts
Yes, for now we need to be pushing to our Docker Hub account, but we may want to look at moving it given.

2021-04-13 03:47 UTC, BenjamenMeyer commented
@stephengtuggy I don't see anything referencing Travis in the Dockerfile or scripts. So it's just a matter of getting the Docker Hub push configured to complete.

2021-04-13 04:21 UTC, BenjamenMeyer commented
@stephengtuggy I think I got this updated for pushing to Docker Hub now. We were actually already doing it; but now the creds are properly in our org GH Secrets. Login is now done via Docker's official Login GH Action. Unfortunately their official GH Action to push to Docker Hub also requires building it with their GH Action; so we still need to use `docker push` in the CI script to upload it.

2021-04-13 04:22 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-release.yml
> +    - name: Upload the artifacts
I think this should be taken care of now.

2021-04-13 04:36 UTC, stephengtuggy approved these changes
Sure enough, the scripts and Dockerfile don't reference anything Travis-specific. Okay, looks good!

2021-04-13 04:36 UTC, merged